# Generated by Django 3.1.1 on 2024-03-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='academic_year',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
