# Generated by Django 4.1.2 on 2024-03-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0002_auto_20240301_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='aadhar_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffs',
            name='area_of_interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='designation',
            field=models.CharField(blank=True, choices=[('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='pan_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='pan_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffs',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Ms', 'Ms')], max_length=10, null=True),
        ),
    ]
