# Generated by Django 3.0.7 on 2024-03-05 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0003_staffs_aadhar_no_staffs_aadhar_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='area_of_interest',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=100)),
                ('year_of_graduation', models.CharField(max_length=4)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='faculty_management_app.Staffs')),
            ],
        ),
    ]
