# Generated by Django 3.0.7 on 2024-03-07 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0004_auto_20240305_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=100)),
                ('book_title', models.CharField(max_length=200)),
                ('publisher_name', models.CharField(max_length=100)),
                ('isbn_no', models.CharField(max_length=20)),
                ('publication_date', models.DateField()),
                ('academic_year', models.CharField(blank=True, max_length=9, null=True)),
                ('affiliation_same', models.BooleanField(default=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_management_app.Staffs')),
            ],
        ),
    ]
