# Generated by Django 3.1.1 on 2024-03-07 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0005_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('isbn_issn', models.CharField(max_length=20)),
                ('month_year', models.CharField(max_length=7)),
                ('doi_if', models.CharField(max_length=255)),
                ('scopus_indexed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('paperlink', models.URLField()),
                ('affiliating_institution', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('scopuslink', models.URLField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_management_app.staffs')),
            ],
        ),
    ]
