# Generated by Django 4.1.2 on 2024-03-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0008_alter_staffs_google_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='staffid',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
