# Generated by Django 3.1.1 on 2024-03-07 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0009_customuser_staffid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='staffid',
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=100)),
                ('book_chapter_title', models.CharField(max_length=200)),
                ('publisher_name', models.CharField(max_length=100)),
                ('isbn_no', models.CharField(max_length=20)),
                ('month_year_publication', models.CharField(max_length=255)),
                ('doi_if', models.CharField(max_length=255)),
                ('is_scopus_indexed', models.BooleanField(default=False)),
                ('paper_link', models.URLField()),
                ('affiliating_institution_same', models.BooleanField(default=True)),
                ('scopus_link', models.URLField()),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_management_app.staffs')),
            ],
        ),
    ]
