# Generated by Django 3.1.1 on 2024-03-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0011_bookchapter_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookchapter',
            name='academic_year',
        ),
    ]
