# Generated by Django 3.1.1 on 2024-03-07 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0013_bookchapter_academic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=255)),
                ('work_title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('filed_applied_date', models.DateField()),
                ('registered_published_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('registration_no', models.CharField(max_length=255)),
                ('dairy_no', models.CharField(max_length=255)),
                ('academic_year', models.CharField(editable=False, max_length=9)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_management_app.staffs')),
            ],
        ),
    ]
