# Generated by Django 3.1.1 on 2024-03-08 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0006_auto_20240307_1317'),
        ('faculty_management_app', '0014_copyright'),
    ]

    operations = [
    ]
