# Generated by Django 3.0.7 on 2024-03-10 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0017_bookchapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookchapter',
            name='affiliating_institution_same',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookchapter',
            name='doi_if',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookchapter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bookchapter',
            name='month_year_publication',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='bookchapter',
            name='paper_link',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bookchapter',
            name='scopus_link',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=255)),
                ('co_authors', models.CharField(max_length=255)),
                ('patent_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('patent_number', models.CharField(max_length=255)),
                ('month_and_year', models.CharField(max_length=7)),
                ('patent_link', models.URLField()),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='patent_proof_files/')),
                ('academic_year', models.CharField(blank=True, max_length=9, null=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_management_app.Staffs')),
            ],
        ),
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.TextField()),
                ('work_title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('filed_applied_date', models.DateField()),
                ('registered_published_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('registration_no', models.CharField(max_length=255)),
                ('dairy_no', models.CharField(max_length=255)),
                ('academic_year', models.CharField(blank=True, max_length=9, null=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_management_app.Staffs')),
            ],
        ),
    ]
