# Generated by Django 3.0.7 on 2024-03-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0018_auto_20240310_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='staffid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
