# Generated by Django 3.1.1 on 2024-03-12 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0019_customuser_staffid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='faculty_management_app.staffs')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_experience', to='faculty_management_app.staffs')),
            ],
        ),
    ]
