# Generated by Django 3.0.7 on 2024-03-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0020_auto_20240312_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentexperience',
            name='designation',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
