# Generated by Django 3.0.7 on 2024-03-13 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0021_auto_20240312_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('affiliating_institute', models.CharField(max_length=255)),
                ('journal_name', models.CharField(max_length=255)),
                ('journal_index', models.CharField(max_length=255)),
                ('other_journal_index', models.CharField(blank=True, max_length=255, null=True)),
                ('journal_type', models.CharField(max_length=255)),
                ('year_of_publication', models.CharField(max_length=255)),
                ('isbn_issn_number', models.IntegerField()),
                ('doi_number', models.CharField(max_length=255)),
                ('scopus_id', models.CharField(max_length=255)),
                ('journal_website', models.URLField()),
                ('journal_pdf', models.FileField(blank=True, null=True, upload_to='conference/pdfs/')),
                ('academic_year', models.CharField(blank=True, max_length=9, null=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_management_app.Staffs')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('affiliating_institute', models.CharField(max_length=255)),
                ('journal_name', models.CharField(max_length=255)),
                ('journal_index', models.CharField(max_length=255)),
                ('other_journal_index', models.CharField(blank=True, max_length=255, null=True)),
                ('journal_type', models.CharField(max_length=255)),
                ('year_of_publication', models.CharField(max_length=255)),
                ('isbn_issn_number', models.IntegerField()),
                ('doi_number', models.CharField(max_length=255)),
                ('scopus_id', models.CharField(max_length=255)),
                ('journal_website', models.URLField()),
                ('journal_pdf', models.FileField(blank=True, null=True, upload_to='journal/pdfs/')),
                ('academic_year', models.CharField(blank=True, max_length=9, null=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_management_app.Staffs')),
            ],
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
