# Generated by Django 3.0.7 on 2024-03-14 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0022_auto_20240313_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizedAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('event', models.CharField(max_length=255)),
                ('event_mode', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('resource_person', models.CharField(max_length=255)),
                ('club_name', models.CharField(max_length=255)),
                ('target_audience', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('report_proof', models.FileField(blank=True, null=True, upload_to='organized_ac_reports/')),
                ('academic_year', models.CharField(blank=True, max_length=9, null=True)),
                ('no_of_days', models.IntegerField(blank=True, null=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_management_app.Staffs')),
            ],
        ),
        migrations.CreateModel(
            name='AttendedAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('event', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('college_name', models.CharField(max_length=255)),
                ('report_proof', models.FileField(blank=True, null=True, upload_to='attended_ac_reports/')),
                ('academic_year', models.CharField(blank=True, max_length=9, null=True)),
                ('no_of_days', models.IntegerField(blank=True, null=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_management_app.Staffs')),
            ],
        ),
    ]
