# Generated by Django 3.1.1 on 2024-03-15 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0023_attendedac_organizedac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=100)),
                ('certification_name', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('completion_date', models.CharField(max_length=10)),
                ('academic_year', models.CharField(blank=True, max_length=9, null=True)),
                ('certificate', models.FileField(upload_to='certificates/')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_management_app.staffs')),
            ],
        ),
    ]
