# Generated by Django 3.1.1 on 2024-03-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0024_auto_20240315_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='journal_type',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='journal_type',
        ),
    ]
