# Generated by Django 4.1.2 on 2024-03-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0026_consultancy_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy_project',
            name='amount',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
