# Generated by Django 4.1.2 on 2024-03-19 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0027_consultancy_project_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Development',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('academic_year', models.CharField(blank=True, max_length=9, null=True)),
                ('Product_name', models.CharField(max_length=255)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_management_app.staffs')),
            ],
        ),
    ]
