# Generated by Django 4.1.2 on 2024-03-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0028_product_development'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_development',
            old_name='Product_name',
            new_name='product_name',
        ),
    ]
