# Generated by Django 4.1.2 on 2024-03-19 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0029_rename_product_name_product_development_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('academic_year', models.CharField(blank=True, max_length=9, null=True)),
                ('funding_agency', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=255)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_management_app.staffs')),
            ],
        ),
    ]
