# Generated by Django 3.1.1 on 2024-03-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0030_project_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
