# Generated by Django 4.1.2 on 2024-03-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0032_remove_certification_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='certification',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('month_and_year', models.CharField(max_length=7)),
                ('cert_pdf', models.FileField(blank=True, null=True, upload_to='achievement/pdfs/')),
                ('academic_year', models.CharField(blank=True, max_length=9, null=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_management_app.staffs')),
            ],
        ),
    ]
