# Generated by Django 4.1.2 on 2024-03-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0033_alter_certification_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='area_of_specialization',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
