# Generated by Django 4.1.2 on 2024-03-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0034_staffs_area_of_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='area_of_specialization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
