# Generated by Django 4.1.2 on 2024-03-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0035_alter_staffs_area_of_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='workplace',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
