# Generated by Django 4.1.2 on 2024-03-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0036_experience_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentexperience',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
