# Generated by Django 4.1.2 on 2024-04-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_management_app', '0038_currentexperience_is_relieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='Qualification_Certificates/'),
        ),
    ]
