
from django.urls import path, include
from . import views
from .import HodViews, StaffViews
from django.conf import settings
from django.conf.urls.static import static
from .HodViews import download_proof
from . import StaffViews


urlpatterns = [
    path('', views.loginPage, name="login"),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('doLogin/', views.doLogin, name="doLogin"),
    path('get_user_details/', views.get_user_details, name="get_user_details"),
    path('logout_user/', views.logout_user, name="logout_user"),
    path('admin_home/', HodViews.admin_home, name="admin_home"),
    path('add_staff/', HodViews.add_staff, name="add_staff"),
    path('add_staff_save/', HodViews.add_staff_save, name="add_staff_save"),
    path('manage_staff/', HodViews.manage_staff, name="manage_staff"),
    path('edit_staff/<staff_id>/', HodViews.edit_staff, name="edit_staff"),
    # path('relieve_staff/<staff_id>/', HodViews.relieve_staff, name="relieve_staff"),
    path('relieve-staff/<int:id>/', HodViews.relieve_staff, name='relieve_staff'),
    path('view_patents/', HodViews.view_patents, name='view_patents'),
    path('download-proof/<path:file_path>/', download_proof, name='download_proof'),
    path('edit_staff_save/', HodViews.edit_staff_save, name="edit_staff_save"),
    path('delete_staff/<staff_id>/', HodViews.delete_staff, name="delete_staff"),
    path('check_email_exist/', HodViews.check_email_exist, name="check_email_exist"),
    path('check_username_exist/', HodViews.check_username_exist, name="check_username_exist"),
    path('admin_profile/', HodViews.admin_profile, name="admin_profile"),
    path('admin_profile_update/', HodViews.admin_profile_update, name="admin_profile_update"),
    path('view_publications/', HodViews.view_publications, name="view_publications"),
    path('view_books/', HodViews.view_books, name='view_books'),
    path('view_journal/', HodViews.view_journal, name='view_journal'),
    path('view_conference/', HodViews.view_conference, name='view_conference'),
    path('view_book_chapters/', HodViews.view_book_chapters, name='view_book_chapters'),
    path('view_copyrights/', HodViews.view_copyrights, name='view_copyrights'),
    path('fetch_publications/', HodViews.fetch_publications, name='fetch_publications'),
    path('view_academic_contribution/', HodViews.view_academic_contribution, name='view_academic_contribution'),
    path('view_attended_AC/', HodViews.view_attended_AC, name='view_attended_AC'),
    path('view_organized_AC/', HodViews.view_organized_AC, name='view_organized_AC'),
    path('view_certifications/', HodViews.view_certifications, name='view_certifications'),
    path('view_achievements/', HodViews.view_achievements, name='view_achievements'),
    path('statistical_table',HodViews.statistical_table,name='statistical_table'),
    path('staff/detail/<int:id>/', HodViews.staff_detail, name='staff_detail'),
    path('aboutus/', HodViews.aboutus, name='aboutus'),
    path('view_projects/',HodViews.view_projects,name='view_projects'),
    path('view_consultancy_project/',HodViews.view_consultancy_project,name='view_consultancy_project'),
    path('view_product_development/',HodViews.view_product_development,name='view_product_development'),
    path('view_project_proposal',HodViews.view_project_proposal,name='view_project_proposal'),
    path('get_publication_counts_by_year', HodViews.get_publication_counts_by_year, name='get_publication_counts_by_year'),
    path('filter_faculty_by_experience', HodViews.filter_faculty_by_experience, name='filter_faculty_by_experience'),

    # URLS for Staff
    path('staff_home/', StaffViews.staff_home, name="staff_home"),
    path('staff_profile/', StaffViews.staff_profile, name="staff_profile"),
    path('staff_add_patent/', StaffViews.staff_add_patent, name='staff_add_patent'),
    path('staff_add_patent_save/', StaffViews.staff_add_patent_save, name='staff_add_patent_save'),
    path('staff_profile_update/', StaffViews.staff_profile_update, name="staff_profile_update"),
    path('qualifications/<staff_id>/', StaffViews.qualifications_view, name='qualifications'),
    path('staff_add_publication/', StaffViews.staff_add_publication, name='staff_add_publication'),
    path('staff_add_journal_save/', StaffViews.staff_add_journal_save, name='staff_add_journal_save'),
    path('staff_add_conference_save/', StaffViews.staff_add_conference_save, name='staff_add_conference_save'),
    path('staff_view_publications/', StaffViews.view_publications, name='staff_view_publications'),
    path('staff_add_book_chapter/', StaffViews.staff_add_book_chapter, name='staff_add_book_chapter'),
    path('staff_add_book_chapter_save/', StaffViews.staff_add_book_chapter_save, name='staff_add_book_chapter_save'),
    path('staff_add_book/', StaffViews.staff_add_book, name='staff_add_book'),
    path('staff_add_book_save/', StaffViews.staff_add_book_save, name='staff_add_book_save'),
    path('staff_add_journal/', StaffViews.staff_add_journal, name='staff_add_journal'),
    path('staff_add_conference/', StaffViews.staff_add_conference, name='staff_add_conference'),
    path('staff_add_copyright/', StaffViews.staff_add_copyright, name='staff_add_copyright'),
    path('staff_add_copyright_save/', StaffViews.staff_add_copyright_save, name='staff_add_copyright_save'),
    path('staff_view_books/', StaffViews.staff_view_books, name='staff_view_books'),
    path('staff_view_journal/', StaffViews.staff_view_journal, name='staff_view_journal'),
    path('staff_view_conference/', StaffViews.staff_view_conference, name='staff_view_conference'),
    path('staff_view_book_chapters/', StaffViews.staff_view_book_chapters, name='staff_view_book_chapters'),
    path('staff_view_copyrights/', StaffViews.staff_view_copyrights, name='staff_view_copyrights'),
    path('staff_view_patent/', StaffViews.staff_view_patent, name='staff_view_patent'),
    path('staff_add_AC/', StaffViews.staff_add_AC, name='staff_add_AC'),
    path('staff_add_organized_AC/',StaffViews.staff_add_organized_AC,name='staff_add_organized_AC'),
    path('staff_add_organized_AC_save', StaffViews.staff_add_organized_AC_save, name='staff_add_organized_AC_save'),
    path('staff_add_attended_AC/',StaffViews.staff_add_attended_AC,name='staff_add_attended_AC'),
    path('staff_add_attended_AC_save/', StaffViews.staff_add_attended_AC_save, name='staff_add_attended_AC_save'),
    path('staff_add_certifications/', StaffViews.staff_add_certifications, name = 'staff_add_certifications'),
    path('staff_add_certifications_save/', StaffViews.staff_add_certifications_save, name = 'staff_add_certifications_save'),
    path('staff_view_certifications/', StaffViews.staff_view_certifications, name='staff_view_certifications'),
    path('staff_view_academic_contribution/', StaffViews.staff_view_academic_contribution, name = 'staff_view_academic_contribution'),
    path('staff_view_attended_AC',StaffViews.staff_view_attended_AC, name='staff_view_attended_AC'),
    path('staff_view_organized_AC', StaffViews.staff_view_organized_AC, name='staff_view_organized_AC'),
    path('staff_aboutus/', StaffViews.staff_aboutus, name='staff_aboutus'),
    path('staff_add_projects/', StaffViews.staff_add_projects, name='staff_add_projects'),
    path('staff_add_consultancy_projects/', StaffViews.staff_add_consultancy_projects,name='staff_add_consultancy_projects'),
    path('staff_add_consultancy_projects_save/', StaffViews.staff_add_consultancy_projects_save,name='staff_add_consultancy_projects_save'),
    path('staff_view_project/',StaffViews.staff_view_project,name='staff_view_project'),
    path('staff_view_consultancy_project/',StaffViews.staff_view_consultancy_project,name='staff_view_consultancy_project'),
    path('staff_add_product_development/',StaffViews.staff_add_product_development,name='staff_add_product_development'),
    path('staff_add_product_development_save/', StaffViews.staff_add_product_development_save, name='staff_add_product_development_save'),
    path('staff_view_product_development/',StaffViews.staff_view_product_development,name='staff_view_product_development'),
    path('staff_add_project_proposal/',StaffViews.staff_add_project_proposal,name='staff_add_project_proposal'),
    path('staff_add_project_proposal_save/', StaffViews.staff_add_project_proposal_save, name='staff_add_project_proposal_save'),
    path('staff_view_project_proposal/',StaffViews.staff_view_project_proposal,name='staff_view_project_proposal'),
    path('staff_add_achievement/', StaffViews.staff_add_achievement, name='staff_add_achievement'),
    path('staff_add_achievement_save/', StaffViews.staff_add_achievement_save, name='staff_add_achievement_save'),
    path('staff_view_achievements/', StaffViews.staff_view_achievements, name='staff_view_achievements'),
    path('delete_journal/<staff_id>/', StaffViews.delete_journal, name="delete_journal"),
    path('delete_conference/<staff_id>/', StaffViews.delete_conference, name="delete_conference"),
    path('delete_book/<staff_id>/', StaffViews.delete_book, name="delete_book"),
    path('delete_book_chapter/<staff_id>/', StaffViews.delete_book_chapter, name="delete_book_chapter"),
    path('delete_patent/<staff_id>/', StaffViews.delete_patent, name="delete_patent"),
    path('delete_copyright/<staff_id>/', StaffViews.delete_copyright, name="delete_copyright"),
    path('delete_attended_AC/<staff_id>/', StaffViews.delete_attended_AC, name="delete_attended_AC"),
    path('delete_organized_AC/<staff_id>/', StaffViews.delete_organized_AC, name="delete_organized_AC"),
    path('delete_certification/<staff_id>/', StaffViews.delete_certification, name="delete_certification"),
    path('delete_consultancy_project/<staff_id>/', StaffViews.delete_consultancy_project, name="delete_consultancy_project"),
    path('delete_product_development/<staff_id>/', StaffViews.delete_product_development, name="delete_product_development"),
    path('delete_project_proposal/<staff_id>/', StaffViews.delete_project_proposal, name="delete_project_proposal"),
    path('delete_achievement/<staff_id>/', StaffViews.delete_achievement, name="delete_achievement"),
    path('contact_us/', StaffViews.contact_us, name="contact_us"),
    path('staff_contact_save/', StaffViews.staff_contact_save, name="staff_contact_save"),
    path('generate-resume/', StaffViews.generate_resume_pdf, name='generate_resume_pdf'),
    path('contact_us/', StaffViews.contact_us, name="contact_us"),
    path('staff_contact_save/', StaffViews.staff_contact_save, name="staff_contact_save"),
    path('success/', StaffViews.success_message, name='success_message'),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
